steps:
- id: build-up
  name: 'docker/compose:1.19.0'
  args: ['-f' , 'dockerTest/docker-compose.yml', 'up', '-d']
- id: tag-ps
  name: 'gcr.io/cloud-builders/docker'
  args: ['images']
  waitFor:
- id: tag-client
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'dockertest_cc-client:latest', 'gcr.io/$PROJECT_ID/testclient:latest']
  waitFor:
- id: tag-redis
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'redis', 'gcr.io/$PROJECT_ID/testredis:latest']
  waitFor:
- id: push-client
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/testclient:latest']
  waitFor:
- id: push-redis
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/testredis:latest']
  waitFor:
- id : deploy-redis
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['create', '-f', 'dockerTest/redis-deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster-3'
  waitFor:
- id : service-redis
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['create', '-f', 'dockerTest/redis-service.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster-3'
  waitFor:
- id : deploy-client
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['create', '-f', 'dockerTest/client-deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster-3'
  waitFor:
- id : service-client
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['expose', 'deployment', 'cc-client', '--type=LoadBalancer', '--port', '4000', '--target-port', '80']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster-3'
  waitFor:
