steps:
- id: build-up
  name: 'docker/compose:1.19.0'
  args: ['up', '-d']
- id: test
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'workspace_cc-client_1' , 'python', '-m', 'nose', 'nosetests/agentTestandSetup.py']
  waitFor:
    - build-up
- id: tag-client
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_cc-client:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME-client:latest']
  waitFor:
      - build-up
      - test
- id: tag-worker
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_rq-worker:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME-worker:latest']
  waitFor:
      - build-up
      - test
      - tag-client
- id: tag-redis
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_redis:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME-redis:latest']
  waitFor:
      - build-up
      - test
      - tag-client
      - tag-worker
- id: push-client
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME-client:latest']
  waitFor:
      - build-up
      - test
      - tag-client
      - tag-worker
      - tag-redis
- id: push-worker
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME-worker:latest']
  waitFor:
      - build-up
      - test
      - tag-client
      - tag-worker
      - tag-redis
      - push-client
- id: push-redis
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME-redis:latest']
  waitFor:
      - build-up
      - test
      - tag-client
      - tag-worker
      - tag-redis
      - push-client
      - push-worker
