steps:
- id: build-up
  name: 'docker/compose:1.19.0'
  args: ['up', '-d']
- id: test
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'workspace_cc-client_1' , 'python' ,'nosetests/testGCB.py']
  waitFor:
    - build-up
- id: deploy
  waitFor:
    - build-up
    - test
