steps:
- id: build-up
  name: 'docker/compose:1.19.0'
  args: ['up', '-d']:
- id: tag-client
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_client:latest', 'gcr.io/$PROJECT_ID/consensuscircle-ang-client:latest']
  waitFor:
- id: tag-worker
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_api:latest', 'gcr.io/$PROJECT_ID/consensuscircle-ang-api:latest']
  waitFor:
- id: tag-redis
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_redis:latest', 'gcr.io/$PROJECT_ID/consensuscircle-ang-redis:latest']
  waitFor:
- id: push-client
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/consensuscircle-ang-client:latest']
  waitFor:
- id: push-worker
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/consensuscircle-ang-api:latest']
  waitFor:
- id: push-redis
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/consensuscircle-ang-redis:latest']
  waitFor:
