steps:
- id: build-up
  name: 'docker/compose:1.19.0'
  args: ['up', '-d']
- id: test
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'workspace_cc-client_1' , 'python', '-m', 'nose', 'nosetests/agentTestandSetup.py']
  waitFor:
- id: tag-client
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_cc-client:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME-client:latest']
  waitFor:
- id: tag-worker
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_rq-worker:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME-worker:latest']
  waitFor:
- id: tag-redis
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_redis:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME-redis:latest']
  waitFor:
- id: push-client
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME-client:latest']
  waitFor:
- id: push-worker
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME-worker:latest']
  waitFor:
- id: push-redis
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME-redis:latest']
  waitFor:
- id : deploy-redis
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['create', '-f', 'buildScripts/redis-deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster-3'
  waitFor:
- id : service-redis
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['create', '-f', 'buildScripts/redis-service.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster-3'
  waitFor:
- id : deploy-rqworker
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['create', '-f', 'buildScripts/rq-worker-deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster-3'
  waitFor:
- id : service-rqworker
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['create', '-f', 'buildScripts/rq-worker-service.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster-3'
  waitFor:
- id : deploy-client
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['create', '-f', 'buildScripts/cc-client-deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster-3'
  waitFor:
- id : service-client
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['expose', 'deployment', 'cc-client', '--type=LoadBalancer', '--port', '5000', '--target-port', '5000']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster-3'
  waitFor:
