steps:
- id: build-up
  name: 'docker/compose:1.19.0'
  args: ['up', '-d']
- id: test
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'workspace_api_1' , 'python', '-m', 'nose', 'nosetests/agentTestandSetup.py']
  waitFor:
- id: tag-client
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_client:latest', 'gcr.io/$PROJECT_ID/consensuscircle-deploy-client:latest']
  waitFor:
- id: tag-api
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_api:latest', 'gcr.io/$PROJECT_ID/consensuscircle-deploy-api:latest']
  waitFor:
- id: tag-worker
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_rq-worker:latest', 'gcr.io/$PROJECT_ID/consensuscircle-deploy-worker:latest']
  waitFor:
- id: tag-redis
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_redis:latest', 'gcr.io/$PROJECT_ID/consensuscircle-deploy-redis:latest']
  waitFor:
- id: push-client
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/consensuscircle-deploy-client:latest']
  waitFor:
- id: push-api
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/consensuscircle-deploy-api:latest']
  waitFor:
- id: push-worker
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/consensuscircle-deploy-worker:latest']
  waitFor:
- id: push-redis
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/consensuscircle-deploy-redis:latest']
  waitFor:
- id : deploytoGKE
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['create', '-f', 'buildScripts/GKElaunch.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=consensuscircle-1'
  waitFor:
