version: '3'
services:
  redis:
    build:
      context: .
      dockerfile: buildScripts/Dockerfile-redis
    expose:
      - "6379"
  rq-worker:
    build:
      context: .
      dockerfile: buildScripts/Dockerfile-worker
    depends_on:
      - redis
    links:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1
  api:
    build:
      context: .
      dockerfile: buildScripts/Dockerfile-API
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - rq-worker
    links:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1
  client:
    build:
      context: .
      dockerfile: buildScripts/Dockerfile-client
    links:
      - api
    depends_on:
      - api
    ports:
      - "3000:3000"
