# Use an official Python runtime as a parent image
FROM python:3.6-slim

# decreases repeated build time as can use the cache instead of having to read from requirements.txt
RUN pip install Flask Redis rq requests ecdsa rejson six nose flask_testing

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME World

RUN cd ./src

WORKDIR ./src

# Run app.py when the container launches
# CMD start.sh
CMD
CMD ["python", "httpAgent.py", "-p", "5000"]
