FROM python:3.6-slim
# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./frontend /app

CMD ["python", "-m", "http.server", "3000"]
