apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: rq-worker
  name: rq-worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rq-worker
    spec:
      containers:
      - env:
        - name: REDIS_URL
          value: redis://redis:6379/1
        image: gcr.io/newagent-e5dac/consensuscircle-worker:latest
        name: rq-worker
        resources: {}
      restartPolicy: Always
status: {}
