FROM python:3.6-alpine

WORKDIR /settings

COPY ./buildScripts/requirements.txt /settings

RUN pip install -r requirements.txt

COPY  ./worker/ /settings
COPY ./agent/convergenceProcessor.py /settings
COPY ./agent/consensusEmulator.py /settings
COPY ./agent/agentUtilities.py /settings
COPY ./agent/redisUtilities.py /settings
COPY ./agent/blockUtilities.py /settings
COPY ./agent/logConfig.json /settings
COPY ./agent/globalsettings.py /settings
COPY ./agent/ccExceptions.py /settings

CMD python worker.py
