# Use an official Python runtime as a parent image
FROM python:3.6-alpine

# Set the working directory to /app
WORKDIR /app

COPY ./buildScripts/requirements.txt /app

# decreases repeated build time as can use the cache instead of having to read from requirements.txt
RUN pip install -r requirements.txt

# Copy the current directory contents into the container at /app
COPY ./agent /app

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "app.py", "-p", "5000"]
